### ISSUE TITLE
Kirbys Dream Land

### ISSUE THREAD

**Issue by jloco** [mattcurrie/gb-save-states#1]
Cannot enter EXTRA MODE, as using the key combo "UP + SELECT + A" always saves a state rather than enabling the option to start a EXTRA game. 

Any way around this?

**Comment by mattcurrie** [comment]
Remapping the key combos on the title screen was straightforward, so have gone with that approach. There's an updated save state patch in the repo now for Kirby's Dream Land.

After applying the new patch you can use `Up + A` to enable the EXTRA game mode from the title screen.

**Comment by jloco** [comment]
Amazing and great work! I should have mentioned there is another key combo for a setting like mode, I *think* it's down-select-b, I don't know if it interferes with that yet, but I thought I should mention it.
Thank you for the fix!

**Comment by mattcurrie** [comment]
Yep, I saw that key combo too when looking through the code, so changed that as well :-) 

So that one is now `Down + B` now to enter the configuration menu.
