### ISSUE TITLE
Requesting: SML1 v1.0 (plus a gift)

### ISSUE THREAD

**Issue by slashinfty** [mattcurrie/gb-save-states#10]
You have a v1.1 patch for Super Mario Land 1, but I am looking for one for v1.0.

Additionally, I'm including a patch for v1.0 of Super Mario Land 2. Credit goes to lightbulbsun.

[sml2_v1_0.zip](https://github.com/mattcurrie/gb-save-states/files/5358411/sml2_v1_0.zip)

**Comment by mattcurrie** [comment]
Hi there,

I've now created a patch for this. Give it a try and let me know if any issues :)

Also thanks for the SML2 patch, I've generated a new v1.0 patch though so that the source is available in here incase its needed later for any updates.
