### ISSUE TITLE
Pokemon Crystal Clear and Silver

### ISSUE THREAD

**Issue by IngwiePhoenix** [mattcurrie/gb-save-states#11]
I am planning to build cartridges using an MBC3 board from InsideGadgets (or alternative build by J. Rodrigez). While browsing through the various discord servers, I came across this one.

Now, the flash card I have in mind also uses 32KB FRAM, but since the Pokémon games were originally also supposed to run on a standard GameBoy (obviously, this kinda excludes Crystal, but its based largely off the predecessors so...maybe) I thought I'd just ask if there was a possibility to add save state support.

The cartridge in question: https://shop.insidegadgets.com/product/gameboy-4mb-32kb-fram-mbc3-with-rtc-flash-cart/

**Comment by mattcurrie** [comment]
It looks like these games use 32KB of SRAM as standard, so there wouldn't be space for the save states on a cart with only 32KB FRAM. 

It might be possible to do save states on a flash cart with 128 KB, however MBC3 doesn't support that much SRAM, so the game would need to be patched to use MBC5 and then there would be no RTC (unless the flash cart maybe supported some kind of weird hybrid mode).
