### ISSUE TITLE
Tiny Toon Adventures 2 - Montana's Movie Madness (U) [!]

### ISSUE THREAD

**Issue by jwLight** [mattcurrie/gb-save-states#12]
Could someone do Tiny Toon Adventures 2 - Montana's Movie Madness (U) [!]?

**Comment by mattcurrie** [comment]
Hi there,

I've now created a patch for this. Give it a try and let me know if any issues :)

**Comment by jwLight** [comment]
Thanks a lot! I will!

**Comment by jwLight** [comment]
Works perfect!!! Thanks a lot!! Could you please make a video on Youtube how to do it yourself? Thanks again!
