### ISSUE TITLE
Zelda color games?

### ISSUE THREAD

**Issue by Too-Ticki** [mattcurrie/gb-save-states#15]
Thanks for all the patches! I'm not sure what the limitations are with the new color patches, but it would be great if someone could create save state patches for the Zelda GBC games, ie Legend of Zelda, The - Link's Awakening DX (U) (V1.2) [C][!], Legend of Zelda, The - Oracle of Ages (U) [C][!], Legend of Zelda, The - Oracle of Seasons (U) [C][!]. Thanks again!

**Comment by 1alien1** [comment]
I second that :)

**Comment by mattcurrie** [comment]
Hi there!

I tried generating a patch for LADX a while back but there was an issue with loading the save state, so I'll need to look into further.

**Comment by 1alien1** [comment]
great, thank you 👍

**Comment by mattcurrie** [comment]
I've now added a patch for Legend of Zelda, The - Link's Awakening DX (U) (V1.2) [C][!].gbc. 

Give it a try and let me know if you see any issues :)

It turns out the problem I was seeing previouly was due to the game having some debug options that can be turned on in the ROM by changing some bytes to non-zero values, and my patch was overwriting them with non-zero values. So once I changed the location of my patch in the ROM it fixed the problem.

**Comment by Too-Ticki** [comment]
Oh wow, I'm so glad you figured it out! I was a bit concerned the button combos might conflict with the in-game saving (which uses select+start+b+a) but all seems to work fine without a hitch. 

I can also report that the larger GBC state saves seem to work fine with the EMS GB USB 64M Smart Card. That card supports Little Sound DJ which also uses 128kb saves, so it makes sense I guess. I tried with this Zelda patch and the Shanghai Pocket patch as single roms, and saving and loading, and the in-game saving all seem to be working fine.

Thanks again for all your work!

**Comment by mattcurrie** [comment]
Thanks for the report that the patches work on the EMS cart!

I've added patches for Oracle of Ages/Seasons. Give them a try and let me know if you see any issues :)

**Comment by Too-Ticki** [comment]
Amazing! Tried both of them and both seem to work just fine. Tried together with the hacks to force GBA mode and GBC palettes and no problem with those either.
Thank you so much!

**Comment by mattcurrie** [comment]
No problem :)
