### ISSUE TITLE
Shanghai Pocket Color

### ISSUE THREAD

**Issue by Too-Ticki** [mattcurrie/gb-save-states#17]
Hi, I was wondering if someone could create a save state patch for Shanghai Pocket (U) (V1.1) [C][!]. Thank you for all your work!

**Comment by mattcurrie** [comment]
Hi there,

I've now created a patch for this. Give it a try and let me know if any issues :)

One thing I noticed is that you need to wait at least until the title screen has displayed before loading the save state, otherwise the audio will be very loud.

**Comment by Too-Ticki** [comment]
Thank you so much for creating this! And thanks for the heads up on the waiting. I tried it out and it seems to work fine!
