### ISSUE TITLE
Hook

### ISSUE THREAD

**Issue by Alex793** [mattcurrie/gb-save-states#18]
Hi, I never finished this game when I was a young boy.

Now I have a modded GBC with IPS screen and an EZ Flash jnr I will be very happy if this game has working save states.

Thanks 👍

**Comment by mattcurrie** [comment]
Hi there,

I've now created a patch for this. Give it a try and let me know if any issues :)

**Comment by Alex793** [comment]
> Hi there,
> 
> I've now created a patch for this. Give it a try and let me know if any issues :)

You are my hero, many thanks it works perfectly 👍

**Comment by mattcurrie** [comment]
That's great, thanks for letting me know :)
