### ISSUE TITLE
Patch for Looney Tunes

### ISSUE THREAD

**Issue by termidr** [mattcurrie/gb-save-states#2]
Can you please make a Patch for Looney Tunes on GB

**Comment by mattcurrie** [comment]
Hi there!

Have generated a patch. Seems to work fine for me, on the first stage at least.

**Comment by termidr** [comment]
Thank You
 

Gesendet: Montag, 25. Juni 2018 um 08:29 Uhr
Von: "Matt Currie" <notifications@github.com>
An: mattcurrie/gb-save-states <gb-save-states@noreply.github.com>
Cc: termidr <termidr@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [mattcurrie/gb-save-states] Patch for Looney Tunes (#2)


Hi there!

Have generated a patch. Seems to work fine for me, on the first stage at least.
