### ISSUE TITLE
MegaMan issue

### ISSUE THREAD

**Issue by nykkos** [mattcurrie/gb-save-states#20]
Hi with the MegaMan serie, all patched files I create don't run properly. The games load but I can't start a new game and can't save.
I follow the process withe bspatch that I use for lots of other games without success.
Could you please help me?
Thank you!

**Comment by Too-Ticki** [comment]
I tested Megaman 1-5 patched with matt's save state patches, and they all start and save fine.  I used this bspatch.exe to apply the bsdiffs: https://www.romhacking.net/utilities/929/

**Comment by nykkos** [comment]
Thank you. That's works now perfectly.
