### ISSUE TITLE
Can someone make a Patch for Pokemon Green (ROM Hack)

### ISSUE THREAD

**Issue by voluptuary** [mattcurrie/gb-save-states#27]
Hi, so I tried to patch my Pokemon Green ROM hacked version of Pokemon Blue with the Blue patch but everything got all garbled, the game loads but things were clearly not right. Would it be possible for someone to make a Patch for the hack @ https://www.romhacking.net/hacks/876/ so basically you would have to apply the patch there then make a patch for that patched ROM. If it's too much work I totally get it. Thanks either way :)

**Comment by mattcurrie** [comment]
Hi there,

I've now created a patch for this. Give it a try and let me know if any issues :)

**Comment by voluptuary** [comment]
Thank you! Works perfectly so far.

**Comment by mattcurrie** [comment]
Awesome :) Thanks for testing!
