### ISSUE TITLE
EU Rom Patch LoZ Oracle of Ages & Oracle of Seasons 

### ISSUE THREAD

**Issue by huuuuuug** [mattcurrie/gb-save-states#28]
I miss a patch for EU Rom for Legend of Zelda, The - Oracle of Ages & Legend of Zelda, The - Oracle of Seasons. 
If you do this, I'll buy you a coffee. Thanks!

**Comment by mattcurrie** [comment]
Hi there,

I've now created patches for these. Give them a try and let me know if any issues :)

**Comment by mattcurrie** [comment]
Hey, that's great it is working for you. Thanks for testing!

No need for the coffee. Enjoy :)
