### ISSUE TITLE
Batman: The Animated Series (1993)

### ISSUE THREAD

**Issue by RetroReef** [mattcurrie/gb-save-states#31]
Really appreciate all the work that’s been done with this project. Would you be able to do this game as well?  Thank you.

**Comment by mattcurrie** [comment]
Hi there,

I've now created a patch for this. Give it a try and let me know if any issues :)

**Comment by RetroReef** [comment]
Wow, that’s was fast. I will test it after work later tonight and get back to you. Thanks!

**Comment by RetroReef** [comment]
Just tested it, and it works great! Thanks, for taking the time to make the patch.

**Comment by mattcurrie** [comment]
That's great :) Thanks for testing.
