### ISSUE TITLE
Store a list of hashes

### ISSUE THREAD

**Issue by Sumidu** [mattcurrie/gb-save-states#32]
Would it be possible to create a "hashes" subdirectory that contains a .txt file for every patch that contains the file-hash of the original rom? That would be super helpful.
Then I could programmatically verify if I have the right file before patching and then trying in an emulator.

**Comment by JonAbrams** [comment]
It would also allow me to add support for save states to [retropatcher](https://retropatcher.jonabrams.com/)

**Comment by Sumidu** [comment]
add pull request with the GB hashes :)

**Comment by mattcurrie** [comment]
Sounds good to me :) Thanks for the PR adding the hashes.

I'll update the scripts so that the `.gb.md5` files are created for future patches.
