### ISSUE TITLE
We need a save patch for dragon slayer!

### ISSUE THREAD

**Issue by Cavencruiser** [mattcurrie/gb-save-states#34]
Dragon slayer on gameboy is a game that requires you to beat a 3 hour long rpg quest without antly saves or passwords. A save state patch will make this game infinitely more playable on real hardware and would be very much appreciated. Thank you!

**Comment by mattcurrie** [comment]
Hey, I've now created a patch for this. I watched someone playing it on YouTube and I still have no idea how to play, but it seems like the patch works when I tested it for a few minutes. Give it a try and let me know if any issues :)
