### ISSUE TITLE
Patch for Gargoyle's Quest II, with English Translation (BPS patch avaible)

### ISSUE THREAD

**Issue by nbercher** [mattcurrie/gb-save-states#36]
The game, "Makai Mura Gaiden - The Demon Darkness", aka Gargoyle's Quest II on Game Boy has been released in Japan and in Japanese language only. A bps patch exists that turn the game into in English language, it is based on the script from the NES version.
The game is hard, like its predecessor and it would be very cool to get a save state capability.
Eg, it would be very much convenient to be able to switch off the Game Boy (save batteries) whenever needed to stop playing instead of loosing progression in the game or trying to get a password from within the game.

**Comment by mattcurrie** [comment]
Hi there,

I've now created a patch for this. Give it a try and let me know if any issues :)
