### ISSUE TITLE
Wetrix (Europe) (En,Fr,De) or Wetrix GB (Japan) (SGB Enhanced) (GB Compatible)

### ISSUE THREAD

**Issue by voluptuary** [mattcurrie/gb-save-states#39]
This is a game that would really be improved with savestate support. They both dont have any save support at all so does that mean they would work on a 32K MBC1\5 cart? The JPN version is GB compatable and basically in english so if you can only do one that would probably give the best results but if the EUR one can be made to work with a 32K cart that would be super awesome too.

**Comment by mattcurrie** [comment]
Hi, 

I've created patches for these. There are patches for both games in the `/patches/cgb` directory. These require a flashcart with 128KB of SRAM. There is also a patch for the JPN version in the `/patches` directory which only requires a flashcart with 32KB of SRAM, but that will only work on the original GB (DMG). If you want to force that 32KB SRAM version to run in DMG mode on a CGB, then it might need additional patching to stop it going into CGB mode. Anyway give them a try and let me know if any issues.
