### ISSUE TITLE
Please use SmokeMonster naming convention or add check sums for the original rom in the name of the patch

### ISSUE THREAD

**Issue by amoore2600** [mattcurrie/gb-save-states#4]
Please use the Smoke Monster Naming convention when naming patches or include a checksum for the original rom in the name of the patch.  This would make scripting much easier to do batches of patches. See Smoke Monster naming convention and check sums here: https://raw.githubusercontent.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/master/EverDrive%20Pack%20SMDBs/EverDrive%20GB%20SMDB.txt

**Comment by mattcurrie** [comment]
I think currently the patches are named using GoodGBx naming convention.  I like your idea of including the md5 hash in the filename, as this would allow renaming to any naming convention given a list of hashes and filenames.

The md5 hash of the original ROM is in the source file for each patch already, so should be straightforward to modify the `create-bsdiff-patch` script to include the md5 hash in the filename of the created patch. 

I'll have a look at it when I get a spare moment 🙂

**Comment by amoore2600** [comment]
I have updated the code to look through files in the "original roms" directory and find a md5sum match.  I thought this was better then renaming files to match. 

Also I have updated the section that creates the bsdiff patch to include the md5sum in the bsdiff patch file name.

I was unable to fully test because wla-gb is giving me the following error: DIRECTIVE_ERROR: Error opening .BACKGROUND file

`#!/bin/sh
#set -x 

function abort {
    echo $1
    echo "\nAborting..."
    exit 1
}

if [[ "$#" -ne 1 ]]; then 
    me=`basename "$0"`
    echo "Usage: ./${me} sourcefile"  
    exit
fi



sourcefile="${PWD}/$1"

# change cwd to the location of this script
cd "${0%/*}"

if [[ ! -e "../patched-roms" ]] ; then
    mkdir ../patched-roms
fi

if [[ ! -e $sourcefile ]] ; then
    abort "\"$1\" not found."
fi


# Finding md5 matching rom 
echo "Finding md5 matching rom"
required_md5=`grep md5 "${sourcefile}" | cut -d " " -f 3`

ls -1 ../original-roms/ | while read i 
do 
test_md5_org_rom=`md5sum ../original-roms/"${i}" | awk '{print$1}'`
   if [ ${test_md5_org_rom} == ${required_md5} ]
      then     
         echo "found match "${i}""
         sourcefile_basename=${sourcefile##*/}
         original_rom_filename=${i%.*}
         original_rom_path="../original-roms/${original_rom_filename}"
         echo "$original_rom_filename${i%.*}.gb" > original_rom_filename.tmp
         echo "${original_rom_path}.gb" > original_rom_path.tmp 
   fi 
done


original_rom_filename=`head -1 original_rom_filename.tmp`
rm original_rom_filename.tmp

original_rom_path=`head -1 original_rom_path.tmp`
rm original_rom_path.tmp

echo "${original_rom_path}"

if [[ ! -e $original_rom_path ]] ; then
    abort "Orignal ROM not found in \"${original_rom_path}\"."
fi


# check if the md5 hash of the original rom is correct
#echo "Verifying md5 hash of \"${original_rom_filename}\"..."
#original_rom_md5=`md5sum "${original_rom_path}" | awk '{print$1}'`
#required_md5=`grep md5 "${sourcefile}" | cut -d " " -f 3`

#if [[ $original_rom_md5 != $required_md5 ]]; then
#    abort "ROM in original-roms directory has md5 hash ${original_rom_md5}. Require ${required_md5}. Aborting..."
#fi


cp "${original_rom_path}" "${original_rom_filename}"


# check if the original rom file size needs padding (required for use of wla's .BACKGROUND directive)
rombanks_directive=(`grep .ROMBANKS "${sourcefile}"`)
expected_file_size=$((rombanks_directive[1] * 16384))
actual_file_size=$((`du -k "${original_rom_path}" | cut -f 1` * 1024))

if [[ $actual_file_size -ne $expected_file_size ]]; then
    echo "Padding ROM to ${expected_file_size} bytes..."

    count=$((expected_file_size/1024))

    # create file of the correct size filled with 0xff bytes
    dd if=/dev/zero ibs=1024 count=${count} of=padded.gb >& /dev/null
    perl -pi -e 's/\x00/\xff/g' padded.gb

    # copy the rom on top of the padded file and move it into place
    dd "if=${original_rom_path}" of=padded.gb conv=notrunc >& /dev/null
    mv padded.gb "${original_rom_filename}"
fi


echo "Assembling patched ROM..."
wla-gb -o "patched.o" "${sourcefile}"

if [ $? -ne 0 ]; then
    rm "${original_rom_filename}"
    abort "Error occurred assembling patched ROM."
fi


# create linkfile
cat >linkfile <<EOL
[objects]
patched.o
EOL

echo "Linking patched ROM..."
wlalink linkfile "patched.gb"

if [ $? -ne 0 ]; then
    rm patched.o
    rm linkfile
    rm "${original_rom_filename}"
    abort "Error occurred linking patched ROM."
fi

echo "Creating patch..."
bsdiff "${original_rom_path}" "patched.gb" "patch.bsdiff"

# move results into place
cp patch.bsdiff "../patches/${original_rom_filename}.${required_md5}.bsdiff"
mv patched.gb "../patched-roms/${original_rom_filename}"

# clean up
rm patch.bsdiff
rm patched.o
rm linkfile
rm "${original_rom_filename}"

echo "Done!"
`

**Comment by mattcurrie** [comment]
Closing this as we now have the new `checksums` directory with a checksum for each game, and an updated `create-bsdiff-patch` which will generate checksum files for new patches going forward.
