### ISSUE TITLE
Corrupt patch

### ISSUE THREAD

**Issue by eba2a03** [mattcurrie/gb-save-states#43]
Every time I use bspatch, I get an error stating "corrupt patch". Tried a few different things, no luck, Curious if I'm overlooking something simple.

**Comment by jedinat** [comment]
This issue is you were probably--like me--right clicking 'save link as' to download the patch. You have to actually open it and download it with the drop down. It should be less than a KB.

**Comment by mattcurrie** [comment]
Thanks @jedinat
