### ISSUE TITLE
Add Zelda Oracle of Seasons and Oracle of Ages - US

### ISSUE THREAD

**Issue by moparisthebest** [mattcurrie/gb-save-states#44]
The built in save/load state on the Everdrive GB X7 doesn't work on these so it would be a good addition.

edit:
specifically the US/Aus versions:
```
c4639cc61c049e5a085526bb6cac03bb  Legend of Zelda, The - Oracle of Ages (USA, Australia).gbc
f2dc6c4e093e4f8c6cbea80e8dbd62cb  Legend of Zelda, The - Oracle of Seasons (USA, Australia).gbc
```

**Comment by Too-Ticki** [comment]
These already exist in the cgb subdirectory:  https://github.com/mattcurrie/gb-save-states/tree/master/patches/cgb

Also the built in saves work on my X7 no problem, maybe check if your roms are corrupt somehow.

**Comment by moparisthebest** [comment]
I think those are the EU versions?

The roms check out sha1sum-wise so no idea...

**Comment by Too-Ticki** [comment]
The description is truncated and talks about several different files, the actual files for the US versions are there tho:
https://github.com/mattcurrie/gb-save-states/blob/master/patches/cgb/Legend%20of%20Zelda%2C%20The%20-%20Oracle%20of%20Ages%20(U)%20%5BC%5D%5B!%5D.gbc.bsdiff
https://github.com/mattcurrie/gb-save-states/blob/master/patches/cgb/Legend%20of%20Zelda%2C%20The%20-%20Oracle%20of%20Seasons%20(U)%20%5BC%5D%5B!%5D.gbc.bsdiff

Maybe try asking at the Everdrive board? Seems there have been some issues with the more recent hardware revisions:
https://krikzz.com/forum/index.php?board=17.0

**Comment by mattcurrie** [comment]
Thanks @Too-Ticki, yes, they're the correct patches. 

I noticed the md5 checksums were missing from the `checksums` directory so I've added those.
