### ISSUE TITLE
Patch Request - The Final Fantasy Legend

### ISSUE THREAD

**Issue by JRB215** [mattcurrie/gb-save-states#5]
I'd love if someone could make a patch for The Final Fantasy Legend.  I see the sequels have patches but not the first. 

Thanks in advance.

**Comment by mattcurrie** [comment]
Hi there,

The Final Fantasy Legend cartridge uses an MBC2 which only supports a maximum of 512 bytes of save RAM, whereas the sequels use MBC1 which can have up to 32KB of save RAM, as required by the save state patches.

I've checked the MBC register writes that the game makes, and it does in fact appear to be compatible with an MBC1 also, so I've created a save state patch for this game which specifies to use MBC1.

Give it a try and let me know if you run into any issues :)
