### ISSUE TITLE
[Patch Request] Wario Land: Super Mario Land 3 Color Edition Patch

### ISSUE THREAD

**Issue by jjfreak** [mattcurrie/gb-save-states#52]
I just wanna say WOW this is EPIC!

Will someone please make a patch for Wario Land: Super Mario Land 3 Color Edition?

https://www.romhacking.net/hacks/6683/

Thanks a lot and keep up the good work!

**Comment by mattcurrie** [comment]
Hi, 

I have created a patch for this game. Let me know if any issues.

**Comment by jjfreak** [comment]
I works perfect and thank you so much for this one 😍
