### ISSUE TITLE
[Request patch] Metroid II DX

### ISSUE THREAD

**Issue by jjfreak** [mattcurrie/gb-save-states#56]
Thanks for making the patch for the Super Mario Land 3 DX!

Any chance of getting a patch for this game: https://www.romhacking.net/hacks/175/

Thanks and keep up the good work!

Cheers 😊

**Comment by mattcurrie** [comment]
Hi,

I've created a patch for this. Give it a try and let me know if any issues.

**Comment by jjfreak** [comment]
Hi,

Thanks a lot and it works perfect as always.

Once again thanks!
