### ISSUE TITLE
Which Romset?

### ISSUE THREAD

**Issue by ahnernoch** [mattcurrie/gb-save-states#59]
Hello, is there any special romset you use for this which already have this patch file naming to do a batch patching? Cheers

**Comment by tyllmoritz** [comment]
Hi @ahnernoch 

I used the following bash commands to copy all roms with a matching checksum from $romdir to original-roms with the correct filename.
I hope it helps.


cd checksums
romdir="../../ROMs"
mkdir -p ../original-roms
for file in *.md5; do cp "$(grep $(cat "$file") <(md5sum "$romdir"/*) | sed -n 's/.*  \(.*\)$/\1/p')" ../original-roms/"${file%.md5}"; done

**Comment by Too-Ticki** [comment]
The naming seems based on the GoodGBx romset. You can look for the GoodTools to rename/check roms.

**Comment by mattcurrie** [comment]
Thanks @Too-Ticki  and @tyllmoritz
