### ISSUE TITLE
[Patch Request] Disney's Atlantis: The Lost Empire (GBC)

### ISSUE THREAD

**Issue by PlayerGameSK** [mattcurrie/gb-save-states#61]
Not entirely sure if this is still being actively maintained in any way, but is there any chance we could get a patch for the GameBoy Color version of Disney's Atlantis: The Lost Empire? Ideally it'd be nice to have one for both the American, as well as the English European version, since I'd like to speedrun the game eventually and there may or may not be some differences that I'll need to check for, but if not, either version would be fine. 

Thanks!

**Comment by mattcurrie** [comment]
Hi, 

I've created patches for these. Give them a try and let me know if any issues.

**Comment by PlayerGameSK** [comment]
Hey,
I don't actually have a GBC/GB flash cart yet, just ran into this looking for things while prepping an SD card for one, and thought I might as well make a request. I'll definitely give this a shot once I do get one though, so thanks a lot for taking the time to create the patches! :)
