### ISSUE TITLE
[Patch Request] Donald Duck - Goin' Quackers

### ISSUE THREAD

**Issue by pocchini** [mattcurrie/gb-save-states#64]
I’m not sure if this is still being actively maintained in any way, but is there any chance we could get a patch for the GameBoy Color version of Donald Duck - Goin' Quackers?

Thank you!

**Comment by mattcurrie** [comment]
Hi, 

I've created a patch for this. Give it a try and let me know if any issues.

**Comment by pocchini** [comment]
Hi,

The patch worked perfectly, and I’m thrilled! Congratulations on such an incredible project. I’ve been studying ways to easily understand how to create my own patches, but I’m struggling with setting up everything needed and getting it to work.

Nevertheless, thank you very much! This feature gives us the opportunity to experiment with the GB library with great fluidity.

Thanks again!

![Imagem do WhatsApp de 2024-10-19 à(s) 09 12 01_0b6afed3](https://github.com/user-attachments/assets/076e7f8a-42a7-4e7d-a94d-9c7e41c87b27)
