### ISSUE TITLE
Unable to run init-patch

### ISSUE THREAD

**Issue by slashinfty** [mattcurrie/gb-save-states#7]
While following the [how-to guide](https://github.com/mattcurrie/gb-save-states/blob/master/src/HOW-TO.md), I can not get `./init-patch` to run without errors (running Debian 10).

First, I had to change `#!/bin/sh` to `#!/bin/bash` in order for it to run at all.

Another problem was `cp "${romfile}" "${original_rom_path}"` since there is no reference to `${romfile}` before, thus it tries to copy an empty string file name.

Last problem was `original_rom_md5=md5 -q "${original_rom_path}"` as `md5` is not a command (there's `md5sum`, but `-q` is not a valid option, and I'm unsure what would be correct with `md5sum`).

**Comment by mattcurrie** [comment]
Thanks, have pushed a fix for the `{$romfile}` reference.

It would be nice if the script detected the presence of either `md5` (which it looks like is macOS specific), or `md5sum`. You should be able to change that line to this:

`original_rom_md5=$(md5sum "${original_rom_path}" | cut -d ' ' -f 1)`
